# Generated by Django 5.2.17 on 2026-09-18 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        db_index=True,
                        default="demo",
                        max_length=4,
                    ),
                ),
                ("make", models.CharField(max_length=80)),
                ("model", models.CharField(max_length=100)),
                ("year", models.PositiveSmallIntegerField()),
                ("coverage_start", models.DateField(null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mode", "make", "model", "year"), name="vehicle_identity"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Recall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        db_index=True,
                        default="demo",
                        max_length=4,
                    ),
                ),
                ("campaign", models.CharField(max_length=80)),
                ("reported_on", models.DateField(db_index=True)),
                ("component", models.CharField(max_length=160)),
                ("summary", models.TextField()),
                ("consequence", models.TextField(blank=True)),
                ("remedy", models.TextField(blank=True)),
                ("payload_hash", models.CharField(blank=True, max_length=64)),
                (
                    "vehicles",
                    models.ManyToManyField(related_name="recalls", to="automotive.vehicle"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("mode", "campaign"), name="recall_campaign")
                ],
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        db_index=True,
                        default="demo",
                        max_length=4,
                    ),
                ),
                ("source_id", models.CharField(max_length=80)),
                ("filed_on", models.DateField(db_index=True)),
                ("incident_on", models.DateField(null=True)),
                ("component", models.CharField(db_index=True, max_length=160)),
                ("narrative", models.TextField(blank=True)),
                ("crash", models.BooleanField(default=False)),
                ("fire", models.BooleanField(default=False)),
                ("injuries", models.PositiveIntegerField(default=0)),
                ("categories", models.JSONField(default=list)),
                ("evidence", models.JSONField(default=dict)),
                ("payload_hash", models.CharField(blank=True, max_length=64)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="automotive.vehicle",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("mode", "source_id"), name="complaint_source")
                ],
            },
        ),
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        db_index=True,
                        default="demo",
                        max_length=4,
                    ),
                ),
                ("component", models.CharField(max_length=160)),
                ("month", models.DateField()),
                ("observed", models.PositiveIntegerField()),
                ("expected", models.FloatField()),
                ("threshold", models.FloatField()),
                ("increase_pct", models.FloatField(null=True)),
                ("severity", models.CharField(max_length=15)),
                ("model_version", models.CharField(default="rolling-v1", max_length=20)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="automotive.vehicle",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vehicle", "component", "month"), name="anomaly_period"
                    )
                ],
            },
        ),
    ]
