# Generated by Django 5.2.17 on 2026-09-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automotive", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="incident_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
