# Generated by Django 5.2.17 on 2026-09-18 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        db_index=True,
                        default="demo",
                        max_length=4,
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("status", models.CharField(default="running", max_length=20)),
                ("loaded", models.PositiveIntegerField(default=0)),
                ("rejected", models.PositiveIntegerField(default=0)),
                ("skipped", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QualityIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_id", models.CharField(max_length=180)),
                ("reason", models.TextField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_id", models.CharField(max_length=180)),
                ("retrieved_at", models.DateTimeField(auto_now_add=True)),
                ("request", models.JSONField(default=dict)),
                ("payload_hash", models.CharField(max_length=64)),
                ("path", models.TextField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_records",
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        db_index=True,
                        default="demo",
                        max_length=4,
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("watermark", models.DateTimeField(null=True)),
                ("last_success", models.DateTimeField(null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("mode", "source"), name="source_state")
                ],
            },
        ),
    ]
