-- Run with a provisioning role; no automatic refresh jobs are activated.
CREATE DATABASE IF NOT EXISTS MOBILITY;
CREATE SCHEMA IF NOT EXISTS MOBILITY.RAW;
CREATE SCHEMA IF NOT EXISTS MOBILITY.SILVER;
CREATE SCHEMA IF NOT EXISTS MOBILITY.GOLD;
CREATE SCHEMA IF NOT EXISTS MOBILITY.EXAMPLES;
CREATE WAREHOUSE IF NOT EXISTS MOBILITY_WH
  WAREHOUSE_SIZE = 'X-SMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;
