USE DATABASE MOBILITY;
CREATE FILE FORMAT IF NOT EXISTS RAW.JSON_FORMAT TYPE=JSON;
CREATE FILE FORMAT IF NOT EXISTS RAW.PARQUET_FORMAT TYPE=PARQUET;
CREATE STAGE IF NOT EXISTS RAW.INGEST_STAGE;
CREATE TABLE IF NOT EXISTS RAW.SOURCE_RECORDS (
  MODE VARCHAR, SOURCE VARCHAR, SOURCE_ID VARCHAR, RETRIEVED_AT TIMESTAMP_TZ,
  PAYLOAD_HASH VARCHAR, REQUEST VARIANT, PAYLOAD VARIANT
);
-- Immutable envelope, populated by upload_raw_snowflake; deduplication is in SILVER.
