USE DATABASE MOBILITY;
CREATE OR REPLACE VIEW SILVER.EARTHQUAKES AS
SELECT r.MODE, feature.VALUE:id::VARCHAR AS SOURCE_ID,
  TO_TIMESTAMP_TZ(feature.VALUE:properties:time::NUMBER / 1000) AS OCCURRED_AT,
  TRY_TO_DOUBLE(feature.VALUE:properties:mag::VARCHAR) AS MAGNITUDE,
  TRY_TO_DOUBLE(feature.VALUE:geometry:coordinates[0]::VARCHAR) AS LONGITUDE,
  TRY_TO_DOUBLE(feature.VALUE:geometry:coordinates[1]::VARCHAR) AS LATITUDE,
  TRY_TO_DOUBLE(feature.VALUE:geometry:coordinates[2]::VARCHAR) AS DEPTH_KM,
  feature.VALUE:properties:place::VARCHAR AS PLACE,
  r.RETRIEVED_AT
FROM RAW.SOURCE_RECORDS r, LATERAL FLATTEN(INPUT => r.PAYLOAD:features) feature
WHERE r.SOURCE='usgs' AND MAGNITUDE BETWEEN 0 AND 10
  AND LATITUDE BETWEEN -90 AND 90 AND LONGITUDE BETWEEN -180 AND 180
QUALIFY ROW_NUMBER() OVER (PARTITION BY r.MODE, SOURCE_ID ORDER BY r.RETRIEVED_AT DESC)=1;
