-- Optional independent ELT demonstration. Not used by the application's publication path.
USE DATABASE MOBILITY;
CREATE DYNAMIC TABLE IF NOT EXISTS EXAMPLES.DAILY_EARTHQUAKES
  TARGET_LAG = DOWNSTREAM WAREHOUSE = MOBILITY_WH INITIALIZE = ON_SCHEDULE
AS SELECT MODE, TO_DATE(OCCURRED_AT) AS EVENT_DATE,
  COUNT(*) AS EVENT_COUNT, MAX(MAGNITUDE) AS MAX_MAGNITUDE
FROM SILVER.EARTHQUAKES GROUP BY MODE, TO_DATE(OCCURRED_AT);
ALTER DYNAMIC TABLE EXAMPLES.DAILY_EARTHQUAKES SUSPEND;
-- Explicit trial-only activation: ALTER DYNAMIC TABLE EXAMPLES.DAILY_EARTHQUAKES REFRESH;
