USE DATABASE MOBILITY;
CREATE STREAM IF NOT EXISTS EXAMPLES.RAW_RECORD_STREAM ON TABLE RAW.SOURCE_RECORDS APPEND_ONLY=TRUE;
CREATE TABLE IF NOT EXISTS EXAMPLES.INGEST_AUDIT (
  MODE VARCHAR, SOURCE VARCHAR, PAYLOAD_HASH VARCHAR, RETRIEVED_AT TIMESTAMP_TZ
);
