-- Tasks are created suspended; no RESUME is issued here.
USE DATABASE MOBILITY;
CREATE TASK IF NOT EXISTS EXAMPLES.AUDIT_INGESTION
  WAREHOUSE=MOBILITY_WH SCHEDULE='60 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('MOBILITY.EXAMPLES.RAW_RECORD_STREAM')
AS MERGE INTO EXAMPLES.INGEST_AUDIT target
USING (SELECT MODE, SOURCE, PAYLOAD_HASH, MAX(RETRIEVED_AT) AS RETRIEVED_AT
       FROM EXAMPLES.RAW_RECORD_STREAM GROUP BY MODE,SOURCE,PAYLOAD_HASH) source
ON target.MODE=source.MODE AND target.SOURCE=source.SOURCE AND target.PAYLOAD_HASH=source.PAYLOAD_HASH
WHEN NOT MATCHED THEN INSERT (MODE,SOURCE,PAYLOAD_HASH,RETRIEVED_AT)
VALUES (source.MODE,source.SOURCE,source.PAYLOAD_HASH,source.RETRIEVED_AT);
