-- Provision with SECURITYADMIN / an equivalent role. Assign roles to actual users separately.
CREATE ROLE IF NOT EXISTS MOBILITY_READER;
CREATE ROLE IF NOT EXISTS MOBILITY_LOADER;
GRANT USAGE ON DATABASE MOBILITY TO ROLE MOBILITY_READER;
GRANT USAGE ON SCHEMA MOBILITY.GOLD TO ROLE MOBILITY_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA MOBILITY.GOLD TO ROLE MOBILITY_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MOBILITY.GOLD TO ROLE MOBILITY_READER;
GRANT USAGE ON WAREHOUSE MOBILITY_WH TO ROLE MOBILITY_READER;
GRANT ROLE MOBILITY_READER TO ROLE MOBILITY_LOADER;
GRANT USAGE ON SCHEMA MOBILITY.RAW TO ROLE MOBILITY_LOADER;
GRANT USAGE ON FILE FORMAT MOBILITY.RAW.PARQUET_FORMAT TO ROLE MOBILITY_LOADER;
GRANT READ, WRITE ON STAGE MOBILITY.RAW.INGEST_STAGE TO ROLE MOBILITY_LOADER;
GRANT SELECT, INSERT ON TABLE MOBILITY.RAW.SOURCE_RECORDS TO ROLE MOBILITY_LOADER;
GRANT INSERT, DELETE ON ALL TABLES IN SCHEMA MOBILITY.GOLD TO ROLE MOBILITY_LOADER;
GRANT CREATE TABLE ON SCHEMA MOBILITY.GOLD TO ROLE MOBILITY_LOADER;
