-- Requires account privileges. Resource monitors cover warehouses, not all account charges.
CREATE RESOURCE MONITOR IF NOT EXISTS MOBILITY_LIMIT
  WITH CREDIT_QUOTA=5 FREQUENCY=MONTHLY START_TIMESTAMP=IMMEDIATELY
  TRIGGERS ON 75 PERCENT DO NOTIFY ON 90 PERCENT DO SUSPEND ON 100 PERCENT DO SUSPEND_IMMEDIATE;
ALTER WAREHOUSE MOBILITY_WH SET RESOURCE_MONITOR=MOBILITY_LIMIT;
SELECT NAME, STATE FROM TABLE(MOBILITY.INFORMATION_SCHEMA.TASK_HISTORY())
ORDER BY SCHEDULED_TIME DESC LIMIT 20;
