# Generated by Django 5.2.17 on 2026-09-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        db_index=True,
                        default="demo",
                        max_length=4,
                    ),
                ),
                ("source", models.CharField(max_length=30)),
                ("source_id", models.CharField(max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[("earthquake", "Earthquake"), ("weather", "Severe weather")],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("expires_at", models.DateTimeField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("magnitude", models.FloatField(blank=True, null=True)),
                ("depth_km", models.FloatField(blank=True, null=True)),
                ("severity", models.FloatField()),
                ("source_updated_at", models.DateTimeField(null=True)),
                ("payload_hash", models.CharField(blank=True, max_length=64)),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mode", "source", "source_id"), name="event_source_id"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__gte", -90),
                            ("latitude__lte", 90),
                            ("longitude__gte", -180),
                            ("longitude__lte", 180),
                        ),
                        name="event_coordinates",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("severity__gte", 0), ("severity__lte", 1)),
                        name="event_severity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("magnitude__isnull", True),
                            models.Q(("magnitude__gte", 0), ("magnitude__lte", 10)),
                            _connector="OR",
                        ),
                        name="event_magnitude",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WeatherReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        db_index=True,
                        default="demo",
                        max_length=4,
                    ),
                ),
                ("location_key", models.CharField(max_length=80)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("valid_at", models.DateTimeField()),
                ("issued_at", models.DateTimeField()),
                ("temperature_c", models.FloatField(null=True)),
                ("precipitation_mm", models.FloatField(null=True)),
                ("wind_kmh", models.FloatField(null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mode", "location_key", "valid_at", "issued_at"),
                        name="weather_reading",
                    )
                ],
            },
        ),
    ]
