# Generated by Django 5.2.17 on 2026-09-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environmental", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
