# Generated by Django 5.2.17 on 2026-09-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        db_index=True,
                        default="demo",
                        max_length=4,
                    ),
                ),
                ("version", models.CharField(max_length=40, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("manifest", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
