# Generated by Django 5.2.17 on 2026-09-18 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        db_index=True,
                        default="demo",
                        max_length=4,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=60)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("code", models.CharField(max_length=30)),
                ("production_capacity", models.PositiveIntegerField()),
                ("utilization", models.FloatField(default=0)),
                ("criticality", models.PositiveSmallIntegerField(default=3)),
                ("product_family", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                        name="supply_chain_factory_lat",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                        name="supply_chain_factory_lon",
                    ),
                    models.UniqueConstraint(fields=("mode", "code"), name="factory_code"),
                    models.CheckConstraint(
                        condition=models.Q(("utilization__gte", 0), ("utilization__lte", 1)),
                        name="factory_utilization",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("criticality__gte", 1), ("criticality__lte", 5)),
                        name="factory_criticality",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LogisticsHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        db_index=True,
                        default="demo",
                        max_length=4,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=60)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                        name="supply_chain_logisticshub_lat",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                        name="supply_chain_logisticshub_lon",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        db_index=True,
                        default="demo",
                        max_length=4,
                    ),
                ),
                ("number", models.CharField(max_length=40)),
                ("description", models.CharField(max_length=180)),
                ("commodity", models.CharField(db_index=True, max_length=60)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("safety_stock_days", models.PositiveSmallIntegerField(default=14)),
                ("criticality", models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("mode", "number"), name="part_number"),
                    models.CheckConstraint(
                        condition=models.Q(("unit_cost__gte", 0)), name="part_cost"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("criticality__gte", 1), ("criticality__lte", 5)),
                        name="part_criticality",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("daily_usage", models.FloatField()),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="supply_chain.factory",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="supply_chain.part",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventorySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("quantity", models.FloatField()),
                ("safety_stock", models.FloatField()),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="supply_chain.requirement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        db_index=True,
                        default="demo",
                        max_length=4,
                    ),
                ),
                ("reference", models.CharField(max_length=50)),
                ("ship_date", models.DateField()),
                ("estimated_arrival", models.DateField(db_index=True)),
                ("actual_arrival", models.DateField(blank=True, null=True)),
                ("shipping_mode", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_transit", "In transit"),
                            ("delayed", "Delayed"),
                            ("delivered", "Delivered"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="supply_chain.factory",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supply_chain.logisticshub",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShipmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="supply_chain.part"
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="supply_chain.shipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        db_index=True,
                        default="demo",
                        max_length=4,
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=160)),
                ("tier", models.PositiveSmallIntegerField(default=1)),
                ("annual_spend", models.DecimalField(decimal_places=2, max_digits=16)),
                ("criticality", models.PositiveSmallIntegerField(default=3)),
                ("reliability", models.FloatField(default=0.95)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("mode", "code"), name="supplier_code"),
                    models.CheckConstraint(
                        condition=models.Q(("annual_spend__gte", 0)), name="supplier_spend"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("criticality__gte", 1), ("criticality__lte", 5)),
                        name="supplier_criticality",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reliability__gte", 0), ("reliability__lte", 1)),
                        name="supplier_reliability",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        db_index=True,
                        default="demo",
                        max_length=4,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=60)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="supply_chain.supplier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sourcing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        choices=[("approved", "Approved"), ("pending", "Pending")],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                ("lead_time_days", models.PositiveSmallIntegerField()),
                ("cost_delta_pct", models.FloatField(default=0)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="supply_chain.part",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="supply_chain.suppliersite",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shipment",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="supply_chain.suppliersite",
            ),
        ),
        migrations.AddConstraint(
            model_name="requirement",
            constraint=models.UniqueConstraint(
                fields=("factory", "part"), name="factory_part_requirement"
            ),
        ),
        migrations.AddConstraint(
            model_name="requirement",
            constraint=models.CheckConstraint(
                condition=models.Q(("daily_usage__gte", 0)), name="requirement_usage"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorysnapshot",
            constraint=models.UniqueConstraint(
                fields=("requirement", "date"), name="inventory_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorysnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0), ("safety_stock__gte", 0)),
                name="inventory_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="shipmentline",
            constraint=models.UniqueConstraint(fields=("shipment", "part"), name="shipment_part"),
        ),
        migrations.AddConstraint(
            model_name="suppliersite",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                name="supply_chain_suppliersite_lat",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliersite",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                name="supply_chain_suppliersite_lon",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliersite",
            constraint=models.UniqueConstraint(
                fields=("supplier", "name"), name="supplier_site_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcing",
            constraint=models.UniqueConstraint(fields=("part", "site"), name="part_site_source"),
        ),
        migrations.AddConstraint(
            model_name="shipment",
            constraint=models.UniqueConstraint(
                fields=("mode", "reference"), name="shipment_reference"
            ),
        ),
        migrations.AddConstraint(
            model_name="shipment",
            constraint=models.CheckConstraint(
                condition=models.Q(("estimated_arrival__gte", models.F("ship_date"))),
                name="shipment_dates",
            ),
        ),
    ]
