# Generated by Django 5.2.17 on 2026-09-18 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("environmental", "0001_initial"),
        ("supply_chain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        db_index=True,
                        default="demo",
                        max_length=4,
                    ),
                ),
                ("as_of", models.DateTimeField(db_index=True)),
                ("model_version", models.CharField(default="weighted-v1", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("score", models.FloatField(db_index=True, null=True)),
                ("classification", models.CharField(max_length=15)),
                ("days_of_supply", models.FloatField(null=True)),
                ("distance_km", models.FloatField(null=True)),
                ("factors", models.JSONField(default=dict)),
                ("stockout_on", models.DateField(null=True)),
                ("explanation", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="environmental.event",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="supply_chain.requirement",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="supply_chain.sourcing",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="risk.calculationrun",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "requirement", "source"), name="assessment_dependency"
                    )
                ],
            },
        ),
    ]
