# Generated by Django 5.2.17 on 2026-09-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="calculationrun",
            constraint=models.UniqueConstraint(
                fields=("mode", "as_of", "model_version"), name="risk_run_version"
            ),
        ),
    ]
